application: cs121owl
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"
